// This file is auto-generated by @hey-api/openapi-ts

export { getReturns, type Options } from './sdk.gen';
export type { ClientOptions, ErrorResponse, GetReturnsData, GetReturnsError, GetReturnsErrors, GetReturnsResponse, GetReturnsResponses, ReturnPoint } from './types.gen';
