// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ErrorResponse
 *
 * Consistent error envelope returned for 4xx/5xx responses.
 */
export type ErrorResponse = {
    /**
     * Detail
     *
     * Human-readable description of the error.
     */
    detail: string;
};

/**
 * ReturnPoint
 */
export type ReturnPoint = {
    /**
     * Date
     *
     * Trading day, formatted YYYY-MM-DD.
     */
    date: string;
    /**
     * Return
     *
     * Daily return as a fraction, close-over-previous-close.
     */
    return: number;
};

export type GetReturnsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Start
         *
         * Start of the range (inclusive), formatted YYYY-MM-DD.
         */
        start: string;
        /**
         * End
         *
         * End of the range (inclusive), formatted YYYY-MM-DD.
         */
        end: string;
    };
    url: '/returns';
};

export type GetReturnsErrors = {
    /**
     * Invalid date range
     */
    400: ErrorResponse;
    /**
     * Malformed query parameters
     */
    422: ErrorResponse;
    /**
     * Upstream data provider error
     */
    502: ErrorResponse;
};

export type GetReturnsError = GetReturnsErrors[keyof GetReturnsErrors];

export type GetReturnsResponses = {
    /**
     * Response Getreturns
     *
     * Successful Response
     */
    200: {
        [key: string]: Array<ReturnPoint>;
    };
};

export type GetReturnsResponse = GetReturnsResponses[keyof GetReturnsResponses];
